// Car http request
// Create car item
POST /cars HTTP/1.1
Content-Type: application/json
Host: {{ host }}
Accept-Language: es

{
  "model": "YAKARTA",
  "cost": 11
}

// List all cars
###
GET /cars HTTP/1.1
Content-Type: application/json
Host: {{ host }}
Accept-Language: es

// Get car by id
### 
GET /cars/614c0b16b74b7fbfb5a0e2cf HTTP/1.1
Content-Type: application/json
Host: {{ host }}
Accept-Language: es

// Update car by id
### 
PUT /cars/614c0b16b74b7fbfb5a0e2cf HTTP/1.1
Content-Type: application/json
Host: {{ host }}
Accept-Language: es

{
  "model": "TESLAPRO",
  "cost": 1000
}