// USER
GET /user/list HTTP/1.1
Content-Type: application/json
Host: {{ host }}
Accept-Language: es

###
GET /user/61418f356afa001fdd4e397b HTTP/1.1
Content-Type: application/json
Host: {{ host }}
Accept-Language: es

// CAR
###
GET /car/list HTTP/1.1
Content-Type: application/json
Host: {{ host }}
Accept-Language: es

### 
GET /car/61423357b40db6397b468b38 HTTP/1.1
Content-Type: application/json
Host: {{ host }}
Accept-Language: es
